// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Custom Temp Mail – Fastest Ad‑Free Disposable Email",
    "description": "Generate a custom temp mail address instantly—choose from multiple domains, no registration, no ads, forever free.",
    "keywords": "temp mail, disposable email, custom mail, fake email, temporary inbox, no ads email, 10minmail, email privacy, free temp mail, temp mail pro, temp mail business",
    "openGraph": {
      "title": "Custom Temp Mail – Pro Features for Business & Devs",
      "description": "Generate a custom temp mail address instantly. Use your own domains with our temp mail pro plan. No ads, forever free option available.",
      "alt": "tempmail.encorebot.me Logo"
    }
  },
  "JsonLd": {
    "name": "tempmail.encorebot.me",
    "description": "tempmail.encorebot.me is a privacy-first disposable email platform for testing, devs, and fast signups. Offers free and pro plans."
  },
  "PageContent": {
    "h1": "How Our Fast & Custom Disposable Temp Mail Technology Works",
    "p1": "In today's world, online services—from free trials to community chats—demand email addresses, exposing you to spam, bots, and unsolicited tracking. <strong>With tempmail.encorebot.me, you get an instant, ad‑free custom temp mail address</strong> across multiple domains—no sign‑up required and always secure.",
    "p2_part1": "<strong>This service is forever free, fully ad‑free, and optimized for speed using lightweight code, edge caching, and global domains.</strong> Learn more about our ",
    "p2_link1": "free & ad‑free promise",
    "p2_part2": " and our ",
    "p2_link2": "PageSpeed‑driven architecture",
    "p2_part3": "."
  },
  "Navigation": {
    "home": "Home",
    "pathnames": "Pathnames"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, de {🇩🇪 Deutsch} en {🇺🇸 English} es {🇪🇸 Español} fr {🇫🇷 Français} hi {🇮🇳 हिन्दी} ru {🇷🇺 Русский} zh {🇨🇳 中文} other {Unknown}}"
  },
  "AppHeader": {
    "api": "API",
    "api_docs": "API - Docs",
    "aria_api_docs": "View API documentation",
    "aria_discord": "Join our Discord community",
    "aria_toggle_theme": "Toggle theme",
    "aria_open_menu": "Open mobile menu",
    "aria_close_menu": "Close mobile menu",
    "github": "GitHub",
    "aria_github": "View GitHub repository",
    "patreon": "Patreon",
    "aria_patreon": "View Patreon",
    "discord": "Discord"
  },
  "EmailBox": {
    "loading": "Loading...",
    "placeholder_username": "username",
    "select_domain": "Select Domain",
    "error_valid_prefix": "Please enter a valid email prefix",
    "copy_email": "Copy email address",
    "show_qr": "Show QR code",
    "refresh": "Refresh",
    "refreshing": "Refreshing",
    "change": "Change",
    "save": "Save",
    "new": "new",
    "delete": "Delete",
    "table_sender": "SENDER",
    "table_subject": "SUBJECT",
    "table_date": "DATE",
    "table_actions": "ACTIONS",
    "inbox_empty_title": "Your inbox is empty",
    "inbox_empty_subtitle": "Waiting for incoming emails. No need to refresh.",
    "view": "View",
    "history_title": "Email History",
    "history_use": "Use",
    "card_header_title": "Generate Your Best Custom Temp Mail Address Instantly",
    "card_header_p": "Avoid spam, phishing, and automated bots with a secure, ad‑free custom temp mail. Keep your real inbox clean and privacy intact—with instant generation, no sign‑up, forever free.",
    "unset_primary": "Unset primary",
    "set_primary": "Set as primary"
  },
  "WhySection": {
    "snippet_title": "What Is “Custom Temp Mail”?",
    "snippet_p": "<strong>Custom temp mail</strong> is your first line of defense in digital privacy. Generate a disposable, ad-free email address instantly from multiple domains. With <strong>tempmail.encorebot.me</strong>, you get a secure temporary email for privacy, spam protection, and fast, anonymous sign-ups. Now with Free and Pro plans for advanced features.",
    "domain_list_title": "tempmail.encorebot.me Domains for Custom Temp Mail",
    "domain_list_p": "Choose from our curated list of domains to ensure your temp mail is always deliverable and never blocked.",
    "updates_title": "From Anonymous Use to Pro Power: New Features",
    "updates_p": "tempmail.encorebot.me has evolved. While anonymous use remains fast and free, you can now log in with your Discord account to unlock powerful new features tailored for regular users, developers, and businesses.",
    "updates_item1_title": "Anonymous Guest",
    "updates_item1_desc": "For quick, one-off tasks. Get an instant temp email with 5-message history and 12-hour storage. No attachments, no login needed.",
    "updates_item2_title": "Discord User",
    "updates_item2_desc": "Log in for more control. Get a 10-message history, 24-hour storage, support for 1MB attachments, and the ability to save important emails to your browser.",
    "updates_item3_title": "Discord Pro for Business & Devs",
    "updates_item3_desc": "The ultimate <strong>temp mail pro</strong> experience. Use your own business domains (e.g., @your-company.com), get 5GB of permanent cloud storage, 25MB attachments, and full API access for seamless integration.",
    "definition_title": "What Is Disposable Temporary Email (Temp Mail)?",
    "definition_p": "A disposable or <strong>temporary email</strong> (also known as <em>temp mail</em>) is a short-lived address for online sign-ups, protecting your real inbox from spam. It's the perfect tool for maintaining privacy. Learn how to <link>create a temp mail address</link> for personal or business use.",
    "use_case_title": "Why Use Custom Temp Mail? From Personal to Business",
    "use_case_item1": "Protect your personal inbox from marketing spam during online shopping.",
    "use_case_item2": "Developers can test user registration flows without cluttering a real inbox.",
    "use_case_item3": "Businesses can use <strong>temp mail with custom domains</strong> for internal testing and quality assurance.",
    "use_case_item4": "Safely access content, download resources, and join communities without revealing your primary email.",
    "checklist_title": "How to Choose the Best Temp Mail Service",
    "checklist_item1": "Instant, custom temporary email addresses with zero registration.",
    "checklist_item2": "A clear, ad-free experience focused on speed and privacy.",
    "checklist_item3": "Support for custom domains for professional <strong>temp mail business</strong> use.",
    "checklist_item4": "Flexible storage options, from temporary Redis to permanent cloud storage.",
    "checklist_item5": "A reliable platform with a public commitment to being forever-free.",
    "checklist_item6": "Advanced features for Pro users, including large attachments and API access.",
    "checklist_p": "<strong>tempmail.encorebot.me</strong> delivers on all fronts, providing a versatile solution that scales from simple, anonymous use to a powerful tool for professionals.",
    "usage_title": "How to Use tempmail.encorebot.me Temp Mail",
    "usage_p1": "Just visit the site, enter a custom name, pick a domain, and your temp mailbox is live. No ads, no sign-up. To unlock more power, simply log in with your WYI account. For details, see our post on <link>creating a temp mail address</link>.",
    "usage_p2": "If an address gets too much spam, delete it and create another in seconds. Your real inbox is always safe.",
    "conclusion_title": "The Best Choice for Custom & Professional Temp Mail",
    "conclusion_p1": "Whether you need a quick burner address or a robust <strong>temp mail pro</strong> solution for your business, tempmail.encorebot.me is designed to meet your needs. We offer unmatched speed, privacy, and flexibility, all without ads.",
    "conclusion_p2": "Explore our <link>best practices guide</link> to get the most out of your temporary email addresses."
  }
};
export default messages;